apiVersion: batch/v1
kind: Job
metadata:
  name: fake-det-pytorch-job
  labels:
    kueue.x-k8s.io/queue-name: x
spec:
  completions: 1
  template:
    metadata:
      name: fake-det-pytorch-pod
    spec:
      restartPolicy: Never
      containers:
      - name: fake-det-pytorch-con
        image: deepfake
        volumeMounts:
          - mountPath: /safe_data
            name: data
          - mountPath: /safe_outputs
            name: results
          - mountPath: /dev/shm
            name: dshm
        resources:
          requests:
            cpu: 8
            memory: '32Gi'
          limits:
            cpu: 16
            memory: '64Gi'
            nvidia.com/gpu: 1
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: fake-det-pytorch-pvc
        - name: results
          persistentVolumeClaim:
            claimName: fake-det-pytorch-pvc
        - name: dshm
          emptyDir:
            medium: Memory
