name: Docker

on:
  push:
    tags:
      - '*'
    branches:
      - '*'

env:
  CI_REGISTRY_IMAGE: ghcr.io/${{ github.repository }}
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  dockerfile-lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    container:
      image: hadolint/hadolint:v2.12.0-debian
    steps:
      - uses: actions/checkout@v4
      - run: hadolint --failure-threshold error Dockerfile

  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      packages: write
    container:
      image: gcr.io/kaniko-project/executor:v1.22.0-debug
      options: --entrypoint ""
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "{\"auths\":{\"ghcr.io\":{\"username\":\"${{ github.actor }}\",\"password\":\"${{ secrets.GITHUB_TOKEN }}\"}}}" > /kaniko/.docker/config.json
          /kaniko/executor \
            --context "${{ github.workspace }}" \
            --dockerfile "${{ github.workspace }}/Dockerfile" \
            --destination "${{ env.CI_REGISTRY_IMAGE }}:${{ env.IMAGE_TAG }}"

  trivy-sbom:
    name: Trivy Scan and SBOM
    runs-on: ubuntu-latest
    needs: build-and-push
    if: startsWith(github.ref, 'refs/tags/')
    container:
      image: aquasec/trivy:0.49.1
      options: --entrypoint ""
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p ~/.docker
          echo "{\"auths\":{\"ghcr.io\":{\"username\":\"${{ github.actor }}\",\"password\":\"${{ secrets.GITHUB_TOKEN }}\"}}}" > ~/.docker/config.json
          trivy image --scanners vuln --format json --output trivy.sbom.json "${{ env.CI_REGISTRY_IMAGE }}:${{ env.IMAGE_TAG }}"
      - uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom
          path: trivy.sbom.json
