name: Docker

on:
  push:
    tags:
      - '*'
    branches:
      - '*'

env:
  CI_REGISTRY_IMAGE: ghcr.io/2bpro/deepfake
  IMAGE_TAG: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'latest' }}

jobs:
  dockerfile-lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --rm -i \
            -v "$PWD/Dockerfile:/Dockerfile" \
            hadolint/hadolint:v2.12.0-debian \
            hadolint --failure-threshold error /Dockerfile

  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --rm \
            -v "$PWD":/workspace \
            -v "$HOME/.docker":/kaniko/.docker \
            -e DOCKER_CONFIG=/kaniko/.docker \
            gcr.io/kaniko-project/executor:v1.22.0-debug \
            --context /workspace \
            --dockerfile /workspace/Dockerfile \
            --destination "${{ env.CI_REGISTRY_IMAGE }}:latest" \
            --destination "${{ env.CI_REGISTRY_IMAGE }}:${{ env.IMAGE_TAG }}"
        env:
          DOCKER_AUTH_CONFIG: >-
            {"auths":{"ghcr.io":{"username":"${{ github.actor }}","password":"${{ secrets.GITHUB_TOKEN }}"}}}

  trivy-sbom:
    name: Trivy Scan and SBOM
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p ~/.docker
          echo "{\"auths\":{\"ghcr.io\":{\"username\":\"${{ github.actor }}\",\"password\":\"${{ secrets.GITHUB_TOKEN }}\"}}}" > ~/.docker/config.json
          docker run --rm \
            -v ~/.docker:/root/.docker \
            -v "$PWD":/project \
            aquasec/trivy:0.49.1 \
            image --scanners vuln \
            --format cyclonedx \
            --output /project/trivy.sbom.json \
            "${{ env.CI_REGISTRY_IMAGE }}:${{ env.IMAGE_TAG }}"
      - uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom
          path: trivy.sbom.json
